Massive cleanup of init.vim, Xresources change and added gruvbox config; fixed setbg script and relative .xprofile line

diff --git a/.local/bin/setbg b/.local/bin/setbg
--- a/.local/bin/setbg
+++ b/.local/bin/setbg
@@ -29,5 +29,13 @@ while true; do
 			shift 2
 			continue
 		;;
+		'--')
+			shift
+			break
+		;;
+		*)
+			echo 'Error!' >&2
+			exit 1
+		;;
 	esac
 done
