sbg: plz work
Former-commit-id: af32c41fcbd9899f6c9b33e560ed7c15c66e5af7
Former-commit-id: 80c68649920150d18a12f526100520ca92b1f101

diff --git a/.local/bin/scripts/sbg b/.local/bin/scripts/sbg
--- a/.local/bin/scripts/sbg
+++ b/.local/bin/scripts/sbg
@@ -12,7 +12,7 @@
 # Dependencies:
 #	- `hsetroot`
 # Optional:
-#	- [`gifsicle` + `shantz-xwinwrap-bzr` + custom `gifbg` and `extcol` scripts] for GIFs;
+#	- [`gifsicle` + `hsetroot` `shantz-xwinwrap-bzr` + custom `gifbg` and `extcol` scripts] for GIFs;
 # -	[`pywal` + custom `vimwal` script] for integration with `wal` and with `wal.vim`
 #	NOTE:
 # - I also use a custom `ifinstalled` script to notify about missing programs
@@ -23,42 +23,6 @@ linknotif() {
 	[ -d "$1" ] && ln -sf "$( find "$(readlink -f "$1")" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc" >/dev/null 2>&1 && notify-send -i "$bgloc" "choosing a nice wallpaper for ya..."
 }
 
-setbg() { # Use gifview for gifs, or else use hsetroot
-	if [ ! -f ~/.cache/wal/active ]; then
-		mime="$( file --dereference --brief --mime-type -- "$bgloc" )"
-		if [ "$mime" = "image/gif" ]; then
-			setsid -f gifbg "$bgloc" && exit 0
-		else
-			hsetroot "${format:--cover}" "$bgloc" >/dev/null
-		fi
-	fi
-}
-
-main() {
-	while getopts ":hi:w:cmt" o; do
-		case "${o}" in
-			h) printf "Usage :\\n'$0'\\n\\t [ -h, -help: Show this message ]\\n\\t [ -i, -input \"path/to/img\" ]\\n\\t [ -w, -wal \"path/to/img\" \"backend\" : use pywal if installed ]\\n\\t [ -c, -center ]\\n\\t [ -m, -maximize: maximize wallpaper ( default format is \"--zoom\" ) ]\\n\\t [ -t, -tile ]\\n" && exit 0 ;;
-
-			i)
-				vimwal -x && dunstreload
-				linknotif "$2"
-				xrdb -load "$XDG_CONFIG_HOME/X11/Xresources" ;;
-
-			w)
-				ifinstalled wal && vimwal -w || exit 1
-				[ -f "$2" ] && linknotif "$2"
-				if [ -n "$2" ]; then backend="$2"; [ -f "$3" ] && linknotif "$3"; fi
-				wal -c && wal --backend "${backend:-wal}" -i "$(readlink -f "$bgloc")" >/dev/null 2>&1 ;;
-
-			c) format="-center" ;;
-			m) format="-full" ;;
-			t) format="-tile" ;;
-
-			*) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
-		esac
-	done
-}
-
 # Initialize target location
 bgloc="${XDG_DATA_HOME:-$HOME/.local/share/}"/bg
 
@@ -66,5 +30,35 @@ bgloc="${XDG_DATA_HOME:-$HOME/.local/share/}"/bg
 pgrep xwinwrap &>/dev/null &&	killall -q xwinwrap
 pgrep xrootgif &>/dev/null &&	killall -q xrootgif
 
-main
-setbg
+while getopts ":hi:w:cmt" o; do
+	case "${o}" in
+		h) printf "Usage :\\n'$0'\\n\\t [ -h, -help: Show this message ]\\n\\t [ -i, -input \"path/to/img\" ]\\n\\t [ -w, -wal \"path/to/img\" \"backend\" : use pywal if installed ]\\n\\t [ -c, -center ]\\n\\t [ -m, -maximize: maximize wallpaper ( default format is \"--zoom\" ) ]\\n\\t [ -t, -tile ]\\n" && exit 0 ;;
+
+		i)
+			vimwal -x
+			linknotif "$2"
+			xrdb -load "$XDG_CONFIG_HOME/X11/Xresources" ;;
+
+		w)
+			ifinstalled wal && vimwal -w || exit 1
+			[ -f "$2" ] && linknotif "$2"
+			if [ -n "$2" ]; then backend="$2"; [ -f "$3" ] && linknotif "$3"; fi
+			wal -c && wal --backend "${backend:-wal}" -i "$(readlink -f "$bgloc")" >/dev/null 2>&1 ;;
+
+		c) format="-center" ;;
+		m) format="-full" ;;
+		t) format="-tile" ;;
+
+		*) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
+	esac
+done
+
+# Use gifview for gifs, or else use hsetroot
+if [ ! -f ~/.cache/wal/active ]; then
+	mime="$( file --dereference --brief --mime-type -- "$bgloc" )"
+	if [ "$mime" = "image/gif" ]; then
+		setsid -f gifbg "$bgloc" && exit 0
+	else
+		hsetroot "${format:--cover}" "$bgloc" >/dev/null
+	fi
+fi
