Simplify `sbg` script
Former-commit-id: fc17422b9846de9efbd6bf1cc6d19401fded3fb1
Former-commit-id: c8c3cd25cbf9524cf6412a258afc75efcdf89551

diff --git a/.local/bin/scripts/sbg b/.local/bin/scripts/sbg
--- a/.local/bin/scripts/sbg
+++ b/.local/bin/scripts/sbg
@@ -1,9 +1,14 @@
 #!/bin/sh
 
-# SLOC: 30
-# Set a background image or gif animation, using pywal to set a terminal colorscheme,or otherwise
-# Supports giving a directory as input, in which case $0 will select a random file from it.
-# using Xresources with xwallpaper, tested mostly on dwm; supports interactive usage.
+# SLOC: 29
+# POSIX compliant script to set images or gif animations as a desktop background,
+# using either pywal to extract a colorscheme for Xresources and (neo)vim, or by
+# simply giving an input file/directory as input; in the latter case $0 will select a random file from it.
+
+## DEPENDENCIES: `xwallpaper`
+## OPTIONAL: [gifsicle+shantz-xwinwrap-bzr+hsetroot+custom `gifbg` and `extcol` scripts] for GIFs;
+##           [pywal+custom `vimwal` script] for integration with `wal` and with `wal.vim`
+## NOTE that I also use a custom `dunstreload` script to automatically reload `dunst` notifications setting colors generated by wal if and only if `wal` was activated.
 
 # 2020 Francesco Minnocci <ascoli.minnocci@gmail.com>
 
@@ -12,40 +17,39 @@
 # NOTE: -w and -i are mutually exclusive (kinda)
 
 bgloc="${XDG_DATA_HOME:-$HOME/.local/share/}"/bg
-format="--zoom"
 killall -q xwinwrap 2>/dev/null
-npw=false
 
 while getopts ":hi:w:mt" o; do
 	case "${o}" in
 		h)
 			printf "Usage :\\n'$0'\\n\\t [ -i, -input \"path/to/img\" ]\\n\\t [ -m, -maximize: maximize wallpaper ( default format is \"--zoom\" ) ]\\n\\t [ -t, -tile ]\\n\\t [ -w, -wal \"path/to/img\" \"backend\" : use pywal if installed ]\\n\\t [ -h, -help: Show this message ]\\n" && exit ;;
+
 		i)
 			vimwal -x && dunstreload
 			[ -f "$2" ] && ln -sf "$(readlink -f "$2")" "$bgloc" >/dev/null 2>&1 && notify-send -i "$bgloc" "Wallpaper changed."
 			[ -d "$2" ] && ln -sf "$( find "$(readlink -f "$2")" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc" >/dev/null 2>&1 && notify-send -i "$bgloc" "choosing a nice wallpaper for ya..."
 			xrdb -load "$XDG_CONFIG_HOME/X11/Xresources" ;;
+
 		w)
 			vimwal -w && dunstreload
 			[ -f "$2" ] && ln -sf "$(readlink -f "$2")" "$bgloc" >/dev/null 2>&1 && notify-send -i "$bgloc" "Wallpaper changed."
 			backend="$3"
-			npw=true
 			command -v wal >/dev/null 2>&1 && wal -c && wal --backend "$backend" -i "$(readlink -f "$bgloc")" >/dev/null 2>&1 ;;
-		m)
-			format="--maximize" ;;
-		t)
-			format="--tile" ;;
-		*)
-			printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
+
+		m) format="--maximize" ;;
+
+		t) format="--tile" ;;
+
+		*) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
 	esac
 done
 
 # Use gifview for gifs, or else xwallpaper
-	if [ $npw ]; then
+	if [ -f ~/.cache/wal/active ]; then
 		mime="$( file --dereference --brief --mime-type -- "$bgloc" )"
 		if [ "$mime" = "image/gif" ]; then
 			setsid -f gifbg "$bgloc"
 		else
-			xwallpaper "$format" "$bgloc"
+			xwallpaper "${format:-zoom}" "$bgloc"
 		fi
 	fi
