Fix colors for readability in man pages
Former-commit-id: 79d6be04d937cf920709fd7bff36c6bfae5ce30c
Former-commit-id: 085b89333aa4f4e3e051421346a7545dd6532a9c

diff --git a/.local/bin/scripts/setbg b/.local/bin/scripts/setbg
--- a/.local/bin/scripts/setbg
+++ b/.local/bin/scripts/setbg
@@ -24,12 +24,11 @@ while getopts ":hi:w:m" o; do
 		w)
 			[ -n "$2" ] && cp "$2" $bgloc > /dev/null 2>&1 && notify-send -i "$bgloc" "Wallpaper changed."
 			backend=$3
-			# exit so xwallpaper is not invoked
-			hash wal &>/dev/null && wal -c && wal --backend $backend -i $bgloc && vimwal -w && exit ;;
+			hash wal &>/dev/null && wal -c && wal --backend $backend -i $bgloc && vimwal -w ;;
 		m)
 			format="--maximize" ;;
 		*)
-			printf "Invalid option: -%s\\n" "$OPTARG" && exit ;;
+			printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
 	esac
 done
 
