New script: `transfer` to utilize transfer.sh (5GB file limit!)
Former-commit-id: ee1ac8cfb95f6bcb9666c503860586dda4114d2c
Former-commit-id: 8be864ed019edb9cc378f2975d81de863aa1598d

diff --git a/.config/zsh/plugins/utils/functionsrc b/.config/zsh/plugins/utils/functionsrc
--- a/.config/zsh/plugins/utils/functionsrc
+++ b/.config/zsh/plugins/utils/functionsrc
@@ -1,4 +1,4 @@
-# vi: ft=zsh
+# vim: ft=zsh
 ## Functions
 # Some of this was stolen, amongst others, from https://github.com/SmartFinn/dotfiles. Thanks!
 
@@ -66,6 +66,15 @@ aurupdate() {
 	git push
 }
 
+# Git
+src_update() {
+	for dir in $dirs; do
+		git -C "$dir" rev-parse --is-inside-work-tree >/dev/null 2>&1 || continue
+		printf '%s: ' "$dir:t"
+		[ "$(($(git -C "$dir" remote | wc -l) > 1))" = "1" ] && { git -C "$dir" fetch --all || printf '%s: Could not fetch upstream...\n' "$dir:t" }
+		git -C "$dir" pull 2>/dev/null || echo "Unable to upgrade."
+	done
+}
 gc() { # Clone and `cd`.
 	git clone $@ && cd $(basename "$1" .git)
 }
@@ -75,15 +84,6 @@ ghc() { # Github clone, personal or otherwise
 	[ -n "$2" ] && ghuser="$1" || ghrepo="$1"
 	[ -z "$ghrepo" ] && ghrepo="$2"
 	git clone git@github.com:${ghuser:-BachoSeven}/$ghrepo.git
-}
-
-src_update() {
-	for dir in $dirs; do
-		git -C "$dir" rev-parse --is-inside-work-tree >/dev/null 2>&1 || continue
-		printf '%s: ' "$dir:t"
-		[ "$(($(git -C "$dir" remote | wc -l) > 1))" = "1" ] && { git -C "$dir" fetch --all || printf '%s: Could not fetch upstream...\n' "$dir:t" }
-		git -C "$dir" pull 2>/dev/null || echo "Unable to upgrade."
-	done
 }
 
 # Updates
@@ -557,7 +557,6 @@ genpasswd() {
 			| head -n "$count"
 	fi
 }
-
 
 # Shellcheck all of my scripts
 scck() {
